# Generated by Django 5.2.7 on 2026-02-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0009_delete_externalstreamingsite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlink',
            name='ads_level',
            field=models.CharField(choices=[('none', 'بدون إعلانات'), ('few', 'إعلانات قليلة'), ('moderate', 'إعلانات متوسطة'), ('heavy', 'إعلانات كثيرة')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='watchlink',
            name='episodes_completeness',
            field=models.CharField(choices=[('complete', 'مكتملة'), ('missing_some', 'تنقصها بعض الحلقات'), ('incomplete', 'غير مكتملة')], default='complete', max_length=20),
        ),
        migrations.AddField(
            model_name='watchlink',
            name='has_arabic_subtitles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watchlink',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
