# Generated by Django 5.2.7 on 2026-05-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0010_watchlink_ads_level_watchlink_episodes_completeness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
