# Generated by Django 6.0.1 on 2026-05-24 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0011_drama_tmdb_id'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='drama',
            name='country',
            field=models.CharField(choices=[('korean', 'كوري'), ('turkish', 'تركي'), ('japanese', 'ياباني'), ('chinese', 'صيني'), ('moroccan', 'مغربي'), ('thai', 'تايلندي')], max_length=50),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='tafarraj_users', related_query_name='tafarraj_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='tafarraj_users', related_query_name='tafarraj_user', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_sites', models.ManyToManyField(blank=True, to='Tafarraj.watchsite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_episode_watched', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='Tafarraj.drama')),
                ('last_watched_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tafarraj.watchsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'drama')},
            },
        ),
        migrations.CreateModel(
            name='SavedDrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('watchlist', 'قائمة المشاهدة'), ('favorites', 'المفضلة'), ('completed', 'شاهدته')], default='watchlist', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='Tafarraj.drama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_dramas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'drama', 'list_type')},
            },
        ),
    ]
