# Generated by Django 6.0.1 on 2026-07-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0012_watchsite_alter_drama_country_customuser_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='mdl_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='mdl_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
