# Generated by Django 6.0.1 on 2026-07-04 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0013_drama_mdl_id_drama_mdl_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='drama',
            name='aired_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='aired_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='content_rating',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='drama',
            name='mdl_popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='mdl_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_arabic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='drama',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Tafarraj.tag'),
        ),
        migrations.CreateModel(
            name='AlternateTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_titles', to='Tafarraj.drama')),
            ],
            options={
                'unique_together': {('drama', 'title')},
            },
        ),
    ]
