# Generated by Django 6.0.1 on 2026-07-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0017_finalize_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=60, null=True, unique=True),
        ),
    ]
