# Generated by Django 6.0.1 on 2026-07-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0018_alter_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='thumbnail_position',
            field=models.CharField(blank=True, default='', help_text="Leave blank for default (top). Or try: center, bottom, top, or '50% 20%'", max_length=20),
        ),
    ]
