# Generated by Django 6.0.1 on 2026-07-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0019_drama_thumbnail_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='homepage_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
