# Generated by Django 6.0.1 on 2026-07-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0020_drama_homepage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='tmdb_popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='tmdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drama',
            name='tmdb_vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
