# Generated by Django 6.0.1 on 2026-08-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0021_add_tmdb_rating_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='quality_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
