# Generated by Django 6.0.1 on 2026-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0022_drama_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='last_mdl_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
