# Generated by Django 6.0.1 on 2026-08-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0023_drama_last_mdl_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='aradrama_checked',
            field=models.BooleanField(default=False),
        ),
    ]
