# Generated by Django 6.0.1 on 2026-08-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tafarraj', '0024_drama_aradrama_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='drama',
            name='ranking_checked',
            field=models.BooleanField(default=False),
        ),
    ]
